provider   = "aws"
aws_region = "us-east-1"
env        = "dev"
account_id = "117183459779"
bucket     = "alsac-tfstate-dev"
key        = "redshift-development/infrastructure.tfstate"
s3_structured_bucket = "alsac-dev-dla-structured"
s3_log_bucket = "alsac-dev-dla-log"