CREATE OR REPLACE VIEW platform_performance_daily_union AS 
SELECT
  'GCM' "source"
, "date"
, "advertiser"
, "site (dcm)" "site_dcm"
, "campaign"
, "placement"
, "placement id" "placement_id"
, "platform type" "platform_type"
, "activity"
, (CASE WHEN ("site (dcm)" = 'Facebook Ad') THEN null ELSE "impressions" END) "impressions"
, (CASE WHEN ("site (dcm)" = 'Bing Ads') THEN 0 WHEN ("site (dcm)" = 'Adwords - Search') THEN 0 WHEN ("site (dcm)" = 'Adwords') THEN 0 ELSE "clicks" END) "clicks"
, "click rate" "click_rate"
, "total conversions" "total_conversions"
, "video completions" "video_completions"
, "view-through conversions" "view_through_conversions"
, "click-through conversions" "click_through_conversions"
, "video first quartile completions" "video_first_quartile_completions"
, "video midpoints" "video_midpoints"
, "video plays" "video_plays"
, "click-through revenue" "click_through_revenue"
, "view-through revenue" "view_through_revenue"
, "total revenue" "total_revenue"
, "click-through conversions + cross-environment" "click_through_conversions_+_cross_environment"
, "click-through revenue + cross-environment" "click_through_revenue_+_cross_environment"
, "total conversions + cross-environment" "total_conversions_+_cross_environment"
, "total revenue + cross-environment" "total_revenue_+_cross_environment"
, "view-through conversions + cross-environment" "view_through_conversions_+_cross_environment"
, "view-through revenue + cross-environment" "view_through_revenue_+_cross_environment"
, ("dbm cost (account currency)" + "media cost") "spend"  -- BIDM-1598: Only 1 column will be populated with values at a time, the other will be 0
, null "platform"
FROM
  performance_marketing_digital_media.gcm_platform_performance_daily
WHERE (("site (dcm)" <> 'DART Search : MSN') AND ("site (dcm)" <> 'DART Search : Google'))
UNION ALL SELECT
  'GCM SA360 Cost Response' "source"
, "date"
, null "advertiser"
, "site (dcm)" "site_dcm"
, "paid search campaign" "campaign"
, "paid search ad group" "placement"
, "paid search ad group id" "placement_id"
, null "platform_type"
, null "activity"
, "paid search impressions" "impressions"
, "paid search clicks" "clicks"
, null "click_rate"
, null "total_conversions"
, null "video_completions"
, null "view_through_conversions"
, null "click_through_conversions"
, null "video_first_quartile_completions"
, null "video_midpoints"
, null "video_plays"
, null "click_through_revenue"
, null "view_through_revenue"
, null "total_revenue"
, null "click_through_conversions_+_cross_environment"
, null "click_through_revenue_+_cross_environment"
, null "total_conversions_+_cross_environment"
, null "total_revenue_+_cross_environment"
, null "view_through_conversions_+_cross_environment"
, null "view_through_revenue_+_cross_environment"
, "paid search cost" "spend"
, null "platform"
FROM
  performance_marketing_digital_media.gcm_sa360_cost_response_daily
UNION ALL SELECT  
 'GCM SA360 Trans' "SOURCE"
, "date"
, null "advertiser"
, "site (dcm)" "site_dcm"
, "paid search campaign" "campaign"
, "paid search ad group" "placement"
, "paid search ad group id" "placement_id"
, null "platform_type"

,(CASE 
   --4possible activity types are condensed into either 'Monthly or One time' 
   WHEN donationMapping.activity = 'donation complete : donation complete - monthly: paid search revenue' THEN 'Monthly'
   WHEN donationMapping.activity = 'donation complete : donation complete - one time: paid search revenue' THEN 'One Time'
   WHEN donationMapping.activity = 'donation complete : donation complete - monthly: paid search transactions' THEN'Monthly'
   WHEN donationMapping.activity = 'donation complete : donation complete - one time: paid search transactions' THEN 'One Time'
   ELSE null END) as "activity"
, null "impressions"
, null "clicks"
, null "click_rate"
, null "total_conversions"
, null "video_completions"
, null "view_through_conversions"
, null "click_through_conversions"
, null "video_first_quartile_completions"
, null "video_midpoints"
, null "video_plays"
, null "click_through_revenue"
, null "view_through_revenue"
, null "total_revenue"
, null "click_through_conversions_+_cross_environment"
, null "click_through_revenue_+_cross_environment" 
, MAX(CASE 
  --activity of "transaction" types are put under the "total_conversions_+_cross_environment" column
   WHEN donationMapping.activity = 'donation complete : donation complete - monthly: paid search transactions' THEN donationMapping.value 
   WHEN donationMapping.activity = 'donation complete : donation complete - one time: paid search transactions' THEN donationMapping.value 
   ELSE null END) as"total_conversions_+_cross_environment"
, MAX(CASE 
  --activity of "revenue" types are put under the "total revenue + cross-environment"  column
   WHEN donationMapping.activity = 'donation complete : donation complete - monthly: paid search revenue' THEN donationMapping.value
   WHEN donationMapping.activity = 'donation complete : donation complete - one time: paid search revenue' THEN donationMapping.value 
   ELSE null END) as "total revenue + cross-environment"  
, null "view_through_conversions_+_cross_environment"
, null "view_through_revenue_+_cross_environment"
, null "spend"
, null "platform"
FROM "performance_marketing_digital_media"."gcm_sa360_transactions_daily"
CROSS JOIN UNNEST(  
  --converts arrays into a flat relation and returns all combinations of the two in order to map the 4 possible activity types to their corresponding values 
  array['donation complete : donation complete - monthly: paid search revenue',
'donation complete : donation complete - monthly: paid search transactions',
'donation complete : donation complete - one time: paid search revenue',
'donation complete : donation complete - one time: paid search transactions'],
                 array["donation complete : donation complete - monthly: paid search revenue",
"donation complete : donation complete - monthly: paid search transactions",
"donation complete : donation complete - one time: paid search revenue",
"donation complete : donation complete - one time: paid search transactions"])  donationMapping(activity, value)
group by
  "date"
, "site (dcm)"
, "paid search campaign" 
, "paid search ad group" 
, "paid search ad group id"
--need to group by the converted activity which is transformed based on the case statement in the select
--SQL can't group by aliases so this case statement must be repeated in order to filter based on its case-then value
, (CASE 
   WHEN donationMapping.activity = 'donation complete : donation complete - monthly: paid search revenue' THEN 'Monthly'
   WHEN donationMapping.activity = 'donation complete : donation complete - one time: paid search revenue' THEN 'One Time'
   WHEN donationMapping.activity = 'donation complete : donation complete - monthly: paid search transactions' THEN'Monthly'
   WHEN donationMapping.activity = 'donation complete : donation complete - one time: paid search transactions' THEN 'One Time'
   ELSE null END)   
UNION ALL SELECT
  'FB' "source"
, "date"
, null "advertiser"
, null "site_dcm"
, "campaign_name" "campaign"
, "adset_name" "placement"
, null "placement_id"
, "device_platform" "platform_type"
, null "activity"
, "impressions"
, null "clicks"
, null "click_rate"
, null "total_conversions"
, null "video_completions"
, null "view_through_conversions"
, null "click_through_conversions"
, null "video_first_quartile_completions"
, null "video_midpoints"
, null "video_plays"
, null "click_through_revenue"
, null "view_through_revenue"
, null "total_revenue"
, null "click_through_conversions_+_cross_environment"
, null "click_through_revenue_+_cross_environment"
, null "total_conversions_+_cross_environment"
, null "total_revenue_+_cross_environment"
, null "view_through_conversions_+_cross_environment"
, null "view_through_revenue_+_cross_environment"
, "spend"
, "publisher_platform" "platform"
FROM
  performance_marketing_digital_media.fb_ads_platform_performance_daily
UNION ALL SELECT
  'AAC' "source"
, "date"
, null "advertiser"
, null "site_dcm"
, "campaign name" "campaign"
, "ad name" "placement"
, null "placement_id"
, "hardware" "platform_type"
, null "activity"
, null "impressions"
, null "clicks"
, null "click_rate"
, null "total_conversions"
, null "video_completions"
, null "view_through_conversions"
, null "click_through_conversions"
, null "video_first_quartile_completions"
, null "video_midpoints"
, null "video_plays"
, null "click_through_revenue"
, null "view_through_revenue"
, null "total_revenue"
, null "click_through_conversions_+_cross_environment"
, null "click_through_revenue_+_cross_environment"
, null "total_conversions_+_cross_environment"
, null "total_revenue_+_cross_environment"
, null "view_through_conversions_+_cross_environment"
, null "view_through_revenue_+_cross_environment"
, "total net spend" "spend"
, null "platform"
FROM
  performance_marketing_digital_media.aac_platform_performance_daily
UNION ALL SELECT
  'GAds' "source"
, "date"
, null "advertiser"
, null "site_dcm"
, "campaign" "campaign"
, "ad_group" "placement"
, null "placement_id"
, "device" "platform_type"
, null "activity"
, null "impressions"
, null "clicks"
, null "click_rate"
, null "total_conversions"
, null "video_completions"
, null "view_through_conversions"
, null "click_through_conversions"
, null "video_first_quartile_completions"
, null "video_midpoints"
, null "video_plays"
, null "click_through_revenue"
, null "view_through_revenue"
, null "total_revenue"
, null "click_through_conversions_+_cross_environment"
, null "click_through_revenue_+_cross_environment"
, null "total_conversions_+_cross_environment"
, null "total_revenue_+_cross_environment"
, null "view_through_conversions_+_cross_environment"
, null "view_through_revenue_+_cross_environment"
, "cost_micros" "spend"
, null "platform"
FROM
  performance_marketing_digital_media.gads_platform_display_daily
UNION ALL SELECT
  'GAdsDISC' "source"
, "date"
, null "advertiser"
, null "site_dcm"
, "campaign" "campaign"
, "ad_group" "placement"
, null "placement_id"
, "device" "platform_type"
, null "activity"
, "impressions"
, null "clicks"
, null "click_rate"
, null "total_conversions"
, null "video_completions"
, null "view_through_conversions"
, null "click_through_conversions"
, null "video_first_quartile_completions"
, null "video_midpoints"
, null "video_plays"
, null "click_through_revenue"
, null "view_through_revenue"
, null "total_revenue"
, null "click_through_conversions_+_cross_environment"
, null "click_through_revenue_+_cross_environment"
, null "total_conversions_+_cross_environment"
, null "total_revenue_+_cross_environment"
, null "view_through_conversions_+_cross_environment"
, null "view_through_revenue_+_cross_environment"
, "cost" "spend"
, null "platform"
FROM
  performance_marketing_digital_media.gads_platform_discovery_daily
UNION ALL SELECT
  'GAdsPS' "source"
, "date"
, null "advertiser"
, null "site_dcm"
, "campaign" "campaign"
, "ad_group" "placement"
, null "placement_id"
, "device" "platform_type"
, null "activity"
, "impressions"
, null "clicks"
, null "click_rate"
, null "total_conversions"
, null "video_completions"
, null "view_through_conversions"
, null "click_through_conversions"
, null "video_first_quartile_completions"
, null "video_midpoints"
, null "video_plays"
, null "click_through_revenue"
, null "view_through_revenue"
, null "total_revenue"
, null "click_through_conversions_+_cross_environment"
, null "click_through_revenue_+_cross_environment"
, null "total_conversions_+_cross_environment"
, null "total_revenue_+_cross_environment"
, null "view_through_conversions_+_cross_environment"
, null "view_through_revenue_+_cross_environment"
, "cost_micros" "spend"
, null "platform"
FROM
  performance_marketing_digital_media.gads_platform_paidsearch_daily
